env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-body-style: ["error", "as-needed"]
  no-use-before-define: ["error", { "functions": false }]
