version: "3"

networks:
  aline-network:
    driver: bridge

services:
  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: "aline.gateway-service"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./gateway:/gateway
      - /gateway/node_modules
    depends_on:
      - data-storage
      - rabbitmq-service
      - redis-service
    networks:
      - aline-network

  data-storage:
    build:
      context: services/data-storage
      dockerfile: Dockerfile
    container_name: "aline.data-storage-service"
    ports:
      - 3001:3001
      - 9230:9230
    volumes:
      - ./services/data-storage:/services/data-storage
      - /services/data-storage/node_modules
    depends_on:
      - rabbitmq-service
      - redis-service
    environment:
      WAIT_HOSTS: rabbitmq-service:5672
    networks:
      - aline-network

  rabbitmq-service:
    image: rabbitmq:3.8-management-alpine
    container_name: "aline.rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - aline-network

  redis-service:
    image: redis:6.0-alpine
    container_name: "aline.redis"
    ports:
    - 6379:6379
    volumes:
      - .docker/redis/redis.conf:/redis.conf
      - .docker/redis:/data
    command: redis-server
    networks:
      - aline-network
